export interface ICompany {
    id?: string,
    name?: string,
    email?: string,
    logoUrl?: string,
    phone?: string,
    website?: string,
    domain?: string,
    spareDomain?: string,
    privacyPolicy?: string,
    termsConditions?: string,
    theme?: string,
    address?: string,
    city?: string,
    postalCode?: string,
    country?: string,
    state?: string,
    timezone?: string,
    relationshipNumber?: string,
    faviconUrl?: string,
    subdomain?: string,
    plan: number,
    currency?: string,
    customerType?: string,
    termsOfServiceVersion?: string,
    termsOfServiceAcceptedBy?: string,
    twilioTrialMode?: boolean,
    twilioFreeCredits?: number,
    termsOfServiceAcceptedDate?: string,
    privacyPolicyVersion?: string,
    privacyPolicyAcceptedBy?: string,
    privacyPolicyAcceptedDate?: string,
    affiliatePolicyVersion?: string,
    affiliatePolicyAcceptedBy?: string,
    affiliatePolicyAcceptedDate?: string,
    isReselling?: boolean,
    onboardingInfo?: string,
    stripeId?: string,
    upgradeEnabledForClients?: boolean,
    cancelEnabledForClients?: boolean,
    autoSuspendEnabled?: boolean,
    saasSettings?: {
        agencyDashboardVisibleTo: string,
        stripeConnectInitiatedBy: string
    },
    stripeActivePlan?: string,
    stripeConnectId?: string,
    enableDepreciatedFeatures?: boolean,
    premiumUpgraded?: boolean,
    status?: string,
    locationCount?: number,
    disableEmailService?: boolean,
    billingInfo?: {
        first_trial_extension_processed_on: string,
        first_trial_extension_reason: string,
        second_trial_extension_processed_on: string,
        second_trial_extension_reason: string,
        pause_subscription_requested_on: string,
        pause_subscription_reason: string,
        pause_subscription_status: string,
        pause_subscription_req_processed_on: string,
        pause_subscription_req_by: string,
        end_trial_early: {
            trial_end_req_by: string,
            trial_ended_on: string
        },
        agency_pro_addon?: {
            is_active: boolean,
            agency_pro_addon_subscription_id: string,
            agency_pro_addon_active_plan: string
        },
        coupons_added?: string[],
        reactivation_attempt?: {
            attempted_on: string,
            attempted_by: string,
            invoice_id: string
        },
        downgrade?: {
            attempted_on: string,
            attempted_by: string,
            previous_plan: string,
            current_plan: string,
            reason: string
        },
        first_payment_date?: string,
        pause_subscription_info: {
            requested_on: string,
            req_by: string,
            reason: string,
            status: string,
            processed_on: string
        }
    }
}
